workflow:
 rules:
   - if: '$CI_PIPELINE_SOURCE == "push"'
     when: never
   - when: always

variables:
  DEBUG: 1
  FETCH_CMD: curl --proto '=https' --proto-redir '=https' --tlsv1.2 --http1.1 -sSfL -o

default:
  tags:
    - qubes-components-updater

stages:
  - prep
  - build

dependencies:
  stage: prep
  script: pip3 install --user -r requirements.txt

### kernel
.kernel-job:
  stage: build
  script: ./kernel-updater.sh

master:
  extends: .kernel-job
  variables:
    BRANCH_linux_kernel: master

stable-5.10:
  extends: .kernel-job
  variables:
    BRANCH_linux_kernel: "stable-5.10"

stable-5.4:
  extends: .kernel-job
  variables:
    BRANCH_linux_kernel: "stable-5.4"

stable-4.19:
  extends: .kernel-job
  variables:
    BRANCH_linux_kernel: "stable-4.19"

### pulseaudio-headers
pulseaudio-headers:
  stage: build
  script: ./pulseaudio-updater.sh

### iso
r4.1-iso:
  stage: build
  script: ./build-iso.sh

r4.1-iso-kernel-latest:
  stage: build
  script: ./build-iso.sh
  variables:
    ISO_USE_KERNEL_LATEST: 1
    ISO_FLAVOR: kernel-latest
