workflow:
 rules:
   - if: '$CI_PIPELINE_SOURCE == "push"'
     when: never
   - when: always

variables:
  DEBUG: 1

.job:
  tags:
    - qubes-kernel-updater
  stage: build
  script: ./kernel-updater.sh

stages:
  - prep
  - build

dependencies:
  tags:
    - qubes-kernel-updater
  stage: prep
  script: pip3 install --user -r requirements.txt

master:
  extends: .job
  variables:
    BRANCH_linux_kernel: master

stable-5.4:
  extends: .job
  variables:
    BRANCH_linux_kernel: "stable-5.4"

stable-4.19:
  extends: .job
  variables:
    BRANCH_linux_kernel: "stable-4.19"

stable-4.14:
  extends: .job
  variables:
    BRANCH_linux_kernel: "stable-4.14"
