stages:
  - prep
  - build

dependencies:
  tags:
    - qubes-kernel-updater
  stage: prep
  script: pip3 install --user -r requirements.txt

master:
  tags:
    - qubes-kernel-updater
  stage: build
  script: DEBUG=1 BRANCH_linux_kernel=master DIST_DOM0=fc25 RELEASE=4.0 ./kernel-updater.sh

stable-5.4:
  tags:
    - qubes-kernel-updater
  stage: build
  script: DEBUG=1 BRANCH_linux_kernel=stable-5.4 DIST_DOM0=fc25 RELEASE=4.0 ./kernel-updater.sh

stable-4.19:
  tags:
    - qubes-kernel-updater
  stage: build
  script: DEBUG=1 BRANCH_linux_kernel=stable-4.19 DIST_DOM0=fc25 RELEASE=4.0 ./kernel-updater.sh

stable-4.14:
  tags:
    - qubes-kernel-updater
  stage: build
  script: DEBUG=1 BRANCH_linux_kernel=stable-4.14 DIST_DOM0=fc25 RELEASE=4.0 ./kernel-updater.sh
