workflow:
 rules:
   - if: '$CI_PIPELINE_SOURCE == "push"'
     when: never
   - when: always

variables:
  DEBUG: 1

default:
  tags:
    - qubes-components-updater

stages:
  - prep
  - build

dependencies:
  stage: prep
  script: pip3 install --user -r requirements.txt

### kernel
.kernel-job:
  stage: build
  script: ./kernel-updater.sh

master:
  extends: .kernel-job
  variables:
    BRANCH_linux_kernel: master

stable-5.10:
  extends: .kernel-job
  variables:
    BRANCH_linux_kernel: "stable-5.10"

stable-5.4:
  extends: .kernel-job
  variables:
    BRANCH_linux_kernel: "stable-5.4"

stable-4.19:
  extends: .kernel-job
  variables:
    BRANCH_linux_kernel: "stable-4.19"

### pulseaudio-headers
pulseaudio-headers:
  stage: build
  script: ./pulseaudio-updater.sh
