workflow:
 rules:
   - if: '$CI_PIPELINE_SOURCE == "push"'
     when: never
   - when: always

variables:
  DEBUG: 1
  FETCH_CMD: curl --proto '=https' --proto-redir '=https' --tlsv1.2 --http1.1 -sSfL -o

default:
  tags:
    - qubes-components-updater

stages:
  - build
  - upload

.component-job:
  stage: build
  rules:
    - if: '$CI_RUN_COMPONENTS_JOBS == "1"'
      when: always
    - when: never

.iso-job:
  before_script: sudo dnf install -y python3-requests python3-pygithub python3-jwt python3-gitlab python3-openqa_client python3-packaging createrepo_c devscripts gpg qubes-gpg-split python3-pyyaml rpm docker python3-docker podman python3-podman reprepro python3-pathspec rpm-sign mktorrent openssl tree mock
  rules:
    - if: '$CI_RUN_ISO_JOBS == "1"'
      when: always
    - when: never

### kernel

.kernel-job:
  extends: .component-job
  before_script: sudo dnf install -y python3-requests python3-packaging python3-pygithub python3-jwt python3-gitlab
  script: ./kernel-updater.sh

linux-main:
  extends: .kernel-job
  variables:
    BRANCH_linux_kernel: main

linux-5.15:
  extends: .kernel-job
  variables:
    BRANCH_linux_kernel: "stable-5.15"

linux-5.10:
  extends: .kernel-job
  variables:
    BRANCH_linux_kernel: "stable-5.10"

linux-5.4:
  extends: .kernel-job
  variables:
    BRANCH_linux_kernel: "stable-5.4"

### pulseaudio-headers

pulseaudio-headers:
  extends: .component-job
  script: ./pulseaudio-updater.sh

### iso

build-iso:
  extends: .iso-job
  stage: build
  script: ./build-iso.sh "$RELEASE"

upload-iso:
  extends: .iso-job
  stage: upload
  script: ./upload-iso.sh "$RELEASE"
  needs:
    - build-iso
