verbose: true

debug: true

backend-vmm: xen

qubes-release: r4.2

use-qubes-repo:
  version: 4.2

gpg-client: qubes-gpg-client-wrapper

distributions:
  - host-fc37

executor:
 type: docker
 options:
   image: "qubes-builder-fedora:latest"

stages:
  - fetch
  - prep
  - build
  - sign:
      executor:
        type: local
  - upload:
      executor:
        type: local

iso:
  kickstart: conf/iso-online-testing.ks

